spring:
  devtools:
    restart:
      enabled: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    hikari:    #springboot2.0整合了hikari ，据说是目前最好的数据库连接池
      username: root
      password: 970912
  jpa:
    hibernate:
      ddl-auto: update  #每次运行程序，没有表格会新建表格，表内有数据不会清空，只会更新
    show-sql: true
